apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.portal.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.portal.name }}
spec:
  replicas: {{ .Values.portal.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.portal.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.portal.name }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Values.portal.name }}
          image: "{{ .Values.portal.image.repository }}:{{ .Values.appVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.portal.port }}
          env:
            # The Portal image serves this url to the Angular app as /config.json
            - name: API_HTTPS
              value: "https://api.{{ .Values.ingress.domain }}"
          resources:
            requests:
              cpu: {{ .Values.portal.resources.requests.cpu | quote }}
              memory: {{ .Values.portal.resources.requests.memory | quote }}
              ephemeral-storage: {{ index .Values.portal.resources.requests "ephemeral-storage" | quote }}
            limits:
              cpu: {{ .Values.portal.resources.limits.cpu | quote }}
              memory: {{ .Values.portal.resources.limits.memory | quote }}
              ephemeral-storage: {{ index .Values.portal.resources.limits "ephemeral-storage" | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.portal.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.portal.name }}
spec:
  selector:
    app: {{ .Values.portal.name }}
  ports:
    - port: {{ .Values.portal.port }}
      targetPort: {{ .Values.portal.port }}
      protocol: TCP